# Generated by Django 4.2.6 on 2024-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_client_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
