# Generated by Django 4.2.6 on 2024-09-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_trainer_birthdate_trainer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='trainer',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
