# Generated by Django 4.2.7 on 2024-09-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=20)),
                ('category', models.CharField(blank=True, help_text='Категория платежа (например, тренировка, абонемент)', max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.client')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
