# Generated by Django 4.2.7 on 2024-09-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('finance', '0002_client_alter_payment_options_alter_payment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
