# Generated by Django 4.2.7 on 2024-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_name_client_first_name_client_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='trainer',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default='Хуй', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='Null', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(default='2000-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(default='2000-01-01', max_length=15),
            preserve_default=False,
        ),
    ]
