# Generated by Django 4.2.7 on 2024-09-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_trainer_photo_alter_trainer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='type',
            field=models.CharField(choices=[('cardio', 'Кардио'), ('strength', 'Силовая'), ('flexibility', 'Растяжка')], default='cardio', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.trainer'),
        ),
    ]
