# Generated by Django 4.2.6 on 2024-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_trainingsession_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='duration',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='end_time',
            field=models.TimeField(default='01:00'),
        ),
    ]
