# Generated by Django 4.2.7 on 2024-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Фамилия', models.CharField(max_length=100)),
                ('Имя', models.CharField(max_length=100)),
                ('Отчество', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('телефон', models.CharField(max_length=15)),
            ],
        ),
    ]
