# Generated by Django 4.2.7 on 2024-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='Фамилия',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='телефон',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='last_name',
            field=models.CharField(default='Говно', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='position',
            field=models.CharField(default='Not specified', max_length=100, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmember',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Зарплата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
