# Generated by Django 4.2.7 on 2024-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staffmember_имя_remove_staffmember_отчество_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество(если есть)'),
        ),
    ]
